### ISSUE TITLE
PIL Image throws new error on large images as of 5.0.0

### ISSUE THREAD

**Issue by RussTorres** [AllenInstitute/render-modules#108]
`PIL.Image.Open` now throws `DecompressionBombError` rather than `DecompressionBombWarning` when trying to open large (default > ~200MB?) images.  This can be changed like so:

```python
from PIL import Image
Image.MAX_IMAGE_PIXELS = None
```

This has caused failures in the make_montage_scapes module, but is probably a bad thing in general for those of us that trust our image files.

**Comment by fcollman** [comment]
is there any reason not to add this to the make_montage_scapes module?

**Comment by RussTorres** [comment]
not really, and I have that implemented in a branch as a patch for Tim.  I'm wondering if having a utility Image module where this is predefined would be more helpful -- so that, for example, integration tests can use it to open the products of modules without an unexpected failure.
