### ISSUE TITLE
pytest skips for non-workflow use cases

### ISSUE THREAD

**Issue by RussTorres** [AllenInstitute/render-modules#190]
It might be helpful to set a condition in which some tests are not run -- integration tests like scaled apply rough alignment and Fiji-based lens correction can add minutes to test runtime and slow down development even if they haven't been touched in a year.  For example, we could test pipeline requirements on feature branches and have the gateway to merging develop -> master be a full test.

This means there are cases where bugfixes need to be added as features to develop, but is likely worth the improved iteration time.

**Comment by RussTorres** [comment]
ps the assignment is to discuss if you think this is an acceptable idea and any tests you think make sense to include.

**Comment by djkapner** [comment]
my workflow is something like this:
- run render-deploy tests on a certain integration_tests/test_xx.py
- if it's taking a long time, I comment out tests that are passing that aren't impacted by the changes I am trying to make.
- once my one test is passing, uncomment. check whole file again.
- maybe ... render-deploy all tests, but usually at this point I push and let bamboo do it.

I'm generally happy with this workflow, as it is simple. Also, if the bamboo build triggered by the push builds, we're generally ok, and the PR review can proceed knowing it won't break. The suggested skips would possibly reveal bugs after a PR to develop goes all the way through. So, I'm not a fan of that

**Comment by mahaling** [comment]
I usually test only the feature I am testing for (like how Dan is doing) and a final test of everything to make sure nothing breaks at the end. 
We do have some tests that are stupid and was solely written for code coverage. I am not sure if we should let bamboo waste time on testing those.

**Comment by RussTorres** [comment]
Thanks for your input -- seems like this is not a pressing issue, and some of the root problems will be addressed with #192 and #193.
