### ISSUE TITLE
updating stacks erases Resolution values

### ISSUE THREAD

**Issue by martinschorb** [AllenInstitute/render-modules#233]
Dear all,

I found that calling `output_tilespecs_to_stack` erases all existing resolution information. This happens both when it creates a new output stack or when modifying an existing one.

I found that something like
```
sR=self.args.get("output_stackVersion") 
            stackResolutionX=sR["stackResolutionX"]
            stackResolutionY=sR["stackResolutionY"]
            stackResolutionZ=sR["stackResolutionZ"]
```

would do the job, but I could not get this value from the input stack.

**Comment by RussTorres** [comment]
Full disclosure, we do not use the stack metadata very much so this is a blind spot in our tests and day-to-day work.  As you point out I did include this in the stack schema, but don't think anyone actually implemented it in the output method.

The reason it overwrites existing values is a bug/typo for which we can put in a PR today -- the link below shows an extra line that uploads a blank stackVersion whether the stack exists or not.
https://github.com/AllenInstitute/render-modules/blob/a447fb020824a21f0a42f942899a4ba07e649602/rendermodules/module/render_module.py#L95


For your use case, would it be helpful to have the `StackTransitionModule` default to copying metadata from the input to output stack by default?  Or is it okay to specify in the input json?

Whatever initial fix we do won't affect modules that don't use the `StackOutputModule` (e.g. "external" modules like the bigfeta solver), so creating the output stack ahead of time might still be a good option for these steps.

**Comment by martinschorb** [comment]
> For your use case, would it be helpful to have the `StackTransitionModule` default to copying metadata from the input to output stack by default?

I guess that would be the expected behavior.

So for the solver, I would simply create an empty stack, specify the resolution and then hand it to bigfeta as the output stack. It will then simply continue with the existing values. Is that correct?

Thanks!
